# Generated by Django 2.1.7 on 2020-04-11 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200410_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='', max_length=2000)),
                ('q_result', models.CharField(default='', max_length=200)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('qpaper_file', models.FileField(upload_to='papers/')),
                ('q_count', models.IntegerField(null=True)),
                ('answer_key', models.CharField(default='', max_length=2000)),
                ('marking_scheme', models.CharField(default='', max_length=200)),
                ('negative_marking_scheme', models.CharField(default='', max_length=200)),
                ('syllabus', models.CharField(default='', max_length=500)),
                ('subject', models.CharField(choices=[('PCM', 'Physics-Chemistry-Maths'), ('P', 'Physics'), ('C', 'Chemistry'), ('M', 'Maths')], default='PCM', max_length=3)),
                ('description', models.CharField(default='', max_length=2000)),
                ('duration', models.IntegerField(null=True)),
                ('max_marks', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paper'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
