# Generated by Django 2.1.7 on 2020-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200411_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='q_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
