# Generated by Django 2.1.7 on 2020-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200412_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='soln_file',
            field=models.FileField(blank=True, upload_to='papers/'),
        ),
    ]
