# Generated by Django 2.1.7 on 2020-04-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paper_soln_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='u_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], default='S', max_length=1),
        ),
    ]
