# Generated by Django 2.1.7 on 2020-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200417_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('F', 'Finished')], default='S', max_length=3),
        ),
        migrations.AddField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='time_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
