# Generated by Django 2.1.7 on 2020-04-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200417_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='submitted_at',
        ),
    ]
