# Generated by Django 2.1.7 on 2020-04-18 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200417_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='time_left',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
