# Generated by Django 2.1.7 on 2020-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200418_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
